In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
print(tf.test.gpu_device_name())

/device:GPU:0


In [5]:
a=tf.constant(5)
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
b=tf.constant([1, 2, 3])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [7]:
c= tf.constant([[1, 2, 3],[3, 4, 5]])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [8]:
d= tf.constant([[[1, 2, 3],[3, 4, 5]]])
d

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]]], dtype=int32)>

In [9]:
b=tf.constant([1, 2, 3])
a=tf.constant([4, 5, 6])
c=tf.add(a,b)
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [10]:
c.numpy()

array([5, 7, 9], dtype=int32)

In [11]:
d=tf.subtract(a, b)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3], dtype=int32)>

In [12]:
m= tf.multiply(a,b)
m

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

In [13]:
b=tf.constant([[1, 2, 3]])
a=tf.constant([[4], [5], [6]])
mm=tf.matmul(b,a)
mm


<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]], dtype=int32)>

In [14]:
b=tf.constant([1, 2, 3])
a=tf.constant([4, 5, 0])
d=tf.divide(b,a)
d

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 ,  inf])>

In [15]:
a=tf.constant([1,3,4])
b=a*2
print(b)
c=a+2
print(c)

tf.Tensor([2 6 8], shape=(3,), dtype=int32)
tf.Tensor([3 5 6], shape=(3,), dtype=int32)


In [17]:
a=tf.constant([1, 2, 3, 4, 5, 6])
a=tf.reshape(a, (2,3))
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [19]:
a=tf.constant([1, 2, 3, 4, 5, 6])
b=tf.expand_dims(a,-1)
b

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [20]:
b=tf.expand_dims(a,0)
b.shape

TensorShape([1, 6])

In [24]:
a=tf.constant([[1,3],[2,4]])
b=tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  9],
       [ 4, 16]], dtype=int32)>

In [29]:
from numpy import float32
c=tf.sqrt(tf.cast(a,dtype=float32))

c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.7320508],
       [1.4142135, 2.       ]], dtype=float32)>

In [31]:
a=tf.constant([[1,3],[2,4.0]])
c=tf.sqrt(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.7320508],
       [1.4142135, 2.       ]], dtype=float32)>

In [34]:
a=tf.constant([[1,3],[2,4]])
b=tf.reduce_min(a, axis= None)
b.numpy()


1

In [36]:
a=tf.constant([[1,3],[2,4]])
b=tf.reduce_min(a, axis= 1)
b.numpy()


array([1, 2], dtype=int32)

In [38]:
a=tf.constant([[1,3],[2,4]])
b=tf.reduce_min(a, axis= 0)
b.numpy()


array([1, 3], dtype=int32)

In [39]:
a=tf.constant([[1,3],[2,4]])
b=tf.reduce_max(a, axis= 0)
b.numpy()


array([2, 4], dtype=int32)

In [42]:
a=tf.constant([[1,3],[2,4]],dtype=float32)
b=tf.reduce_mean(a)
b.numpy()


2.5

In [44]:
a=tf.constant([[1,3],[2,4]])
b=tf.reduce_mean(a)
b.numpy()


2

In [45]:
import numpy as np
a=np.array([[1,3],[2,4]])
a.mean()

2.5

In [52]:
a=tf.constant([[1,3],[2,4]],dtype=float32)
std=tf.math.reduce_std(a)
std.numpy()

1.1180339

In [53]:
sum=tf.reduce_sum(a)
sum

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>